# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_protobuf.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'message_protobuf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16message_protobuf.proto\"+\n\tMyRequest\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\x0c\x12\r\n\x05\x61rray\x18\x02 \x03(\x05\"\x1c\n\nMyResponse\x12\x0e\n\x06result\x18\x01 \x01(\t22\n\tMyService\x12%\n\x08MyMethod\x12\n.MyRequest\x1a\x0b.MyResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_protobuf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MYREQUEST']._serialized_start=26
  _globals['_MYREQUEST']._serialized_end=69
  _globals['_MYRESPONSE']._serialized_start=71
  _globals['_MYRESPONSE']._serialized_end=99
  _globals['_MYSERVICE']._serialized_start=101
  _globals['_MYSERVICE']._serialized_end=151
# @@protoc_insertion_point(module_scope)
